<?php
/**
 * Created by lqdung1992.
 * Date: 3/1/2018
 * Time: 12:54 PM
 */
namespace Plugin\BannerSimple\Repository;

use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityRepository;
use Eccube\Repository\AbstractRepository;
use Plugin\BannerSimple\Entity\Banner;

/**
 * BannerSimple repo.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends AbstractRepository
{
    public function __construct(ManagerRegistry $registry, string $entityClass = Banner::class)
    {
        parent::__construct($registry, $entityClass);
    }

    public function getBanners()
    {
        $qb = $this->createQueryBuilder('b');
        $qb = $qb->where('b.type = :type')
            ->setParameter('type', Banner::BANNER);
        $qb->orderBy('b.sort_no', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function getSliders()
    {
        $qb = $this->createQueryBuilder('b');
        $qb = $qb->where('b.type = :type')
            ->setParameter('type', Banner::SLIDER);
        $qb->orderBy('b.sort_no', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
