<?php
namespace Plugin\BannerSimple\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BannerSimple repo.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
}
